# SwiftLint configuration for xcsift

# Exclude these paths from linting
excluded:
  - .build
  - SourcePackages

# Enable specific rules
opt_in_rules:
  - todo
  - mark

# Configure warning severity
todo: warning

# Line length
line_length:
  warning: 200
  error: 300

# Function body length
function_body_length:
  warning: 150
  error: 300

# Type body length
type_body_length:
  warning: 500
  error: 800
