import ArgumentParser
import Foundation

/// Options that shape how build output is parsed and rendered.
///
/// Declared as a shared `@OptionGroup` on both the root command and `xcsift mcp`. Do not re-declare
/// these flags on the subcommand: ArgumentParser lets the root command consume its own options
/// wherever they appear on the command line, so a re-declared `--warnings` would always read as
/// `false` inside the subcommand. Sharing one `ParsableArguments` type is what makes the root's
/// decoded value flow down (swift-argument-parser matches a previously decoded group by type).
struct SiftingOptions: ParsableArguments {
    @Option(name: .long, help: "Path to configuration file (default: auto-detect .xcsift.toml)")
    var config: String?

    @Flag(name: [.short, .long], help: "Print detailed warnings list (by default only warning count is shown)")
    var warnings: Bool = false

    @Flag(
        name: [.customShort("W"), .customLong("Werror")],
        help: "Treat warnings as errors (build fails if warnings present)"
    )
    var warningsAsErrors: Bool = false

    @Flag(name: [.short, .long], help: "Include code coverage data (auto-converts .profraw files)")
    var coverage: Bool = false

    @Option(name: .long, help: "Path to code coverage directory or JSON file (default: auto-detect in .build/)")
    var coveragePath: String?

    @Flag(name: .long, help: "Include detailed per-file coverage data (default: summary only)")
    var coverageDetails: Bool = false

    @Flag(name: [.short, .long], help: "Include executable targets generated by the build")
    var executable: Bool = false

    @Flag(name: .long, help: "Include per-target build phases and timing")
    var buildInfo: Bool = false

    @Option(
        name: [.customShort("f"), .long],
        help: "Output format (json, toon, or github-actions). Default: json. On CI, annotations are auto-appended."
    )
    var format: FormatType?

    @Option(name: .long, help: "TOON delimiter (comma, tab, or pipe). Default: comma")
    var toonDelimiter: TOONDelimiterType?

    @Option(
        name: .long,
        help:
            "TOON key folding (disabled or safe). Default: disabled. When safe, nested single-key objects collapse to dotted paths"
    )
    var toonKeyFolding: TOONKeyFoldingType?

    @Option(name: .long, help: "TOON flatten depth limit for key folding. Default: unlimited")
    var toonFlattenDepth: Int?

    @Option(
        name: .long,
        help: "Threshold in seconds for slow test detection (e.g., 1.0). Tests exceeding this are marked as slow."
    )
    var slowThreshold: Double?

    @Flag(name: .long, help: "Parse xcbeautify/Tuist-formatted input ([x], [!], ✔, ✖ markers)")
    var xcbeautify: Bool = false

    init() {}

    /// Merges these options with the configuration file, with CLI values winning.
    func resolve(quiet: Bool = false, exitOnFailure: Bool = false) throws -> ResolvedConfig {
        let fileConfig = try ConfigLoader().loadConfig(explicitPath: config)

        return ConfigMerger.merge(
            config: fileConfig,
            cliFormat: format,
            cliWarnings: warnings,
            cliWarningsAsErrors: warningsAsErrors,
            cliQuiet: quiet,
            cliCoverage: coverage,
            cliCoverageDetails: coverageDetails,
            cliCoveragePath: coveragePath,
            cliSlowThreshold: slowThreshold,
            cliBuildInfo: buildInfo,
            cliExecutable: executable,
            cliExitOnFailure: exitOnFailure,
            cliToonDelimiter: toonDelimiter,
            cliToonKeyFolding: toonKeyFolding,
            cliToonFlattenDepth: toonFlattenDepth,
            cliXcbeautify: xcbeautify
        )
    }
}
